name: Run Playwright test Checkout app

on:
  repository_dispatch:
    types: ["run-checkout-tests"]
  pull_request:
    branches:
      - main

jobs:
  run_automation_tests:
    if: contains(github.event.pull_request.labels.*.name, 'checkout')
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: The-Quality-Group/end-to-end-tests
          ref: main

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: |
          npx playwright install-deps
          npx playwright install chromium
      
      - name: Run checkout tests
        run: |
          mkdir -p allure-results
          ALLURE_RESULTS_DIR=allure-results 
          DEBUG=pw:api xvfb-run npx playwright test tests/checkout --project=chrome --reporter=allure-playwright
      
      - name: Generate Allure report
        run: npx allure generate allure-results --clean -o allure-report

      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
